db:
  image: postgres:9.4
  # build: ./postgres
  #mem_limit: 1000m
  ports:
    - "5432:5432"
  env_file: docker.env

web:
  build: .
  #command: bundle exec puma  -t 5:5 -p 3000 --preload
  command: bundle exec passenger start --port 3000 # --log-file my.log
  #mem_limit: 2000m
  volumes:
    - .:/edfu
    #- /opt/edfu/data/upload:edfu/data/upload
  ports:
    - "80:3000"
    - "3000:3000"

#storage:
#  image: busybox
#  volumes:
#    - /var/lib/docker/storage
#  command: true

#haproxy:
#  build: .
#  command: .
#  hostname: active-proxy
#  volumes:
#    - ./haproxy/haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg:ro
#  ports:
#    - "80:80"

#nginx:
#  image: nginx
#  ports: 80:80
