db:
  image: postgres:9.4
  # build: ./postgres
  environment:
    - POSTGRESQL_USER=postgres
    - POSTGRESQL_PASS=postgres
  ports:
    - "5432:5432"
  #volumes_from:
  #  - storage


solr:   # change this and create your own solr image
  image: makuk66/docker-solr:4.10.4
  #command: /bin/bash -c '/opt/solr/bin/solr -e cloud; echo hit return to quit; read'
  # hostname: solr
  #domainname: localdomain
  ports:
    - "8983:8983"
  volumes:
    - ./config/solr/schema.xml:/opt/solr/example/solr/collection1/conf/schema.xml
  environment:
    - JAVA_OPTS="-server -Xms512M -Xmx1792M -XX:MaxPermSize=768M"
    #- RACK_ENV=development
    #- PORT=3000
    #- SESSION_SECRET=
    #- DEBUG=true


#nginx:
#  image: nginx
#  ports: 80:80

web:
  build: .
  command: bundle exec puma  -t 15:15 -p 3000 -e development
  #command: bundle exec puma  -t 5:5 -p 3000 -e production
  #command: bundle exec rails server -p 3000 -b 0.0.0.0
  hostname: edfu
  volumes:
    - .:/edfu
    - /opt/edfu/data/upload:edfu/data/upload
  ports:
    - "80:3000"
  links:
    - db:db
    - redis:redis
    - solr:solr

#haproxy:
#  build: .
#  command: .
#  hostname: active-proxy
#  volumes:
#    - ./haproxy/haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg:ro
#  ports:
#    - "80:80"



#mongo:
#  image: mongodb
#  ports:
#    - "28017:28017"
#    - "27018:27018"
#    - "27017:27017"