db:
  image: postgres:9.4
  # build: ./postgres
  #mem_limit: 1000m
  environment:
    - POSTGRESQL_USER=postgres
    - POSTGRESQL_PASS=postgres
  ports:
    - "5432:5432"


solr:
  image: makuk66/docker-solr:4.10.4
  #mem_limit: 2000m
  ports:
    - "8983:8983"
  volumes:
    - ./config/solr/schema.xml:/opt/solr/example/solr/collection1/conf/schema.xml
  environment:
    - JAVA_OPTS="-server -Xms512M -Xmx1792M -XX:MaxPermSize=768M"

web:
  build: .
  command: bundle exec puma  -t 5:5 -p 3000 --preload
  #mem_limit: 2000m
  volumes:
    - .:/edfu
    #- /opt/edfu/data/upload:edfu/data/upload
  ports:
    - "80:3000"
    - "3000:3000"
  links:
    - db:db
    - solr:solr

#storage:
#  image: busybox
#  volumes:
#    - /var/lib/docker/storage
#  command: true

#haproxy:
#  build: .
#  command: .
#  hostname: active-proxy
#  volumes:
#    - ./haproxy/haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg:ro
#  ports:
#    - "80:80"

#nginx:
#  image: nginx
#  ports: 80:80
