defaults: &defaults
  users: # user_name/e-mail must be unique in the db, password length >= 8)
    -
      user_name: admin@edfu.de
      user_password: adminadmin
    -
      user_name: panzer@sub.uni-goettingen.de
      user_password: adminadmin
    -
      user_name: graeff@edfu.de
      user_password: g_edfu_import
    -
      user_name: beucke@edfu.de
      user_password: b_edfu_import

  edfu_formular_sheet: Tabelle1
  edfu_topo_sheet: Tabelle1
  edfu_god_sheet: Tabelle1
  edfu_word_sheet: Tabelle1

development:
  <<: *defaults

test:
  <<: *defaults

production:
  <<: *defaults