production:
  solr:
    hostname: localhost
    port: 8983
    log_level: WARNING
    path: /solr/collection1/
    # read_timeout: 2
    # open_timeout: 0.5

development:
  solr:
    hostname: localhost
    port: 8983
    log_level: INFO
    path: /solr/collection1/

test:
  solr:
    hostname: localhost
    port: 8983
    log_level: WARNING
    path: /solr/collection1/
    